version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
      - echo Install node.js types
      - npm install --save-dev @types/node

  build:
    commands:
      - echo Running build...
      - npm run build

artifacts:
  base-directory: 'dist'
  files:
    - '**/*'